# statusbar - (https://github.com/c-mueller/statusbar)
# Copyright (c) 2018 Christian Müller <cmueller.dev@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
workspace:
  base: /go
  path: src/github.com/c-mueller/statusbar

pipeline:
  load_deps:
    image: golang:${GO_VERSION}
    commands:
      # Install Fish shell
      - apt-get update && apt-get install -y fish
      # Install Godep
      - go get -u github.com/golang/dep/cmd/dep
      # Install Dependencies
      - ./update_deps.fish
      # Build application
      - ./build.fish
  test_and_benchmark:
    image: golang:${GO_VERSION}
    commands:
      - go test -race -coverprofile=profile.out -covermode=atomic -v -cover -bench=. -benchtime=10s ./...
  codecov_report:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
  cloc_report:
    image: halive/git-cloc:latest
    commands:
      - cloc $(git ls-files)
github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - statusbar
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    when:
      event: tag

matrix:
  GO_VERSION:
    - "1.10"
