workspace:
  base: /go
  path: src/github.com/c-mueller/statusbar

pipeline:
  load_deps:
    image: golang:${GO_VERSION}
    commands:
      # Install Godep
      - go get -u github.com/golang/dep/cmd/dep
      # Install Dependencies
      - dep ensure -v
  build:
    image: golang:${GO_VERSION}
    commands:
      - go build -v
  test_and_benchmark:
    image: golang:${GO_VERSION}
    commands:
      - go test -v -cover -bench=. -benchtime=10s ./...
  cloc_report:
    image: halive/git-cloc:latest
    commands:
      - cloc $(git ls-files)

matrix:
  GO_VERSION:
    - "1.10"
    - "1.9"
