# statusbar - (https://github.com/c-mueller/statusbar)
# Copyright (c) 2018 Christian Müller <cmueller.dev@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
refresh_interval: 500
components:
  - identifier: hostname
    type: Hostname
  - identifier: uptime_block
    type: Block
    spec:
      components:
        - identifier: uptime_label
          type: Text
          short_mode_hidden: true
          custom_separator: true
          separator: " "
          spec:
            text: "UP:"
        - identifier: uptime
          type: Uptime
  - identifier: cpu_block
    type: Block
    spec:
      components:
        - identifier: cpu_message
          type: Text
          custom_separator: true
          separator: " "
          spec:
            text: "CPU:"
        - identifier: cpu
          type: CPULoadBar
          spec:
            update_interval: 500
  - identifier: memory
    type: Memory
    spec:
      invert: true
      show_swap: false
      show_bytes: false
  - identifier: network
    type: Network
    short_mode_hidden: false
    spec:
      interface_name: eth0
      update_interval: 500
      recent_count: 20
      global: true
      show_total: False
  - identifier: player_info
    type: Block
    spec:
      components:
        - identifier: plctl_artist
          custom_separator: true
          separator: " - "
          type: Command
          spec:
            command: "playerctl metadata artist"
            execution_interval: 1000
        - identifier: plctl_title
          type: Command
          spec:
            command: "playerctl metadata title"
            execution_interval: 1000
  - identifier: time_block
    type: Block
    spec:
      components:
        - identifier: date_message
          type: Text
          custom_separator: true
          separator: " "
          spec:
            text: "TIME:"
        - identifier: clock
          type: Clock
          spec:
            blink: true
