#!/usr/bin/env fish

echo "Updating Dependencies"

dep ensure -v

echo "Writing 'dep_info.go'"

echo "// statusbar - (https://github.com/c-mueller/statusbar)" > dep_info.go
echo "// Copyright (c) 2018 Christian Müller <cmueller.dev@gmail.com>." >> dep_info.go
echo "//" >> dep_info.go
echo "// This program is free software: you can redistribute it and/or modify" >> dep_info.go
echo "// it under the terms of the GNU General Public License as published by" >> dep_info.go
echo "// the Free Software Foundation, either version 3 of the License, or" >> dep_info.go
echo "// (at your option) any later version." >> dep_info.go
echo "//" >> dep_info.go
echo "// This program is distributed in the hope that it will be useful," >> dep_info.go
echo "// but WITHOUT ANY WARRANTY; without even the implied warranty of" >> dep_info.go
echo "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the" >> dep_info.go
echo "// GNU General Public License for more details." >> dep_info.go
echo "//" >> dep_info.go
echo "// You should have received a copy of the GNU General Public License" >> dep_info.go
echo "// along with this program.  If not, see <http://www.gnu.org/licenses/>." >> dep_info.go

echo "" >> dep_info.go
echo "// WARNING: THIS FILE IS AUTOGENERATED AND WILL GET OVERWRITTEN WHEN RUNNING 'update_deps.fish'" >> dep_info.go
echo // LAST EXECUTION: (date) GIT REVISION: (git rev-parse HEAD) >> dep_info.go
echo "package main" >> dep_info.go
echo "" >> dep_info.go
echo var depInfo = `(dep status -json)` >> dep_info.go